services:
  # 1. Base de données PostgreSQL
  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - chatbot-net

  # 2. Backend NestJS
  chat-backend:
    build: ./chat-backend
    container_name: chat-backend-1
    ports:
      - "3000:3000" 
    env_file:
      - .env
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/chatbot_db?schema=public
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - chatbot-net

  # 3. Frontend React (Vite)
  frontend:
    build: ./chat-frontend
    container_name: chat-frontend-1
    ports:
      - "5173:5173"
    depends_on:
      - chat-backend
    restart: unless-stopped
    networks:
      - chatbot-net

volumes:
  postgres_data:

networks:
  chatbot-net:
    driver: bridge
  